server:
  port: 443
  context-path: /
  tomcat:
    uri-encoding: UTF-8
  ssl:
    key-store: classpath:www.amazingxu.xyz.jks
    key-store-password: XXff05141125
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://193.112.72.214:3306/auShop?useSSL=false&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false&characterEncoding=UTF-8
    username: root
    password: XXff05141125
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true

  mail:
    host: smtp.qq.com
    username: 121894598@qq.com
    password: ifgmsmqhamnrbiic
    default-encoding: UTF-8
